import com.ftn.sbnz.model.FinalnaDijagnoza;
import com.ftn.sbnz.model.Preparat;
import com.ftn.sbnz.model.Bolest;
import com.ftn.sbnz.model.enums.FazaBiljke;
import com.ftn.sbnz.model.enums.PotkategorijaPreparata;
import com.ftn.sbnz.model.Preporuka;
import java.time.LocalDate;
import com.ftn.sbnz.model.Biljka;
import com.ftn.sbnz.model.enums.KategorijaPreparata;
import com.ftn.sbnz.model.enums.KategorijaBiljke;
import com.ftn.sbnz.event.NeizlecenaBolestVoca;
import com.ftn.sbnz.event.UgrozenaBiljka


rule "alarm NeizlecenaBolestVoca se javio bar 3 puta u roku od 6 meseci → aktivirati alarm UgrozenaBiljka"
    no-loop
    when
        $neizlecen_bolest: NeizlecenaBolestVoca(
                                                $biljka: biljka, 
                                                $bolest: bolest,  
                                                $fazaBiljke : fazaJavljanja, 
                                                $preparat: preparat
                                            ) over window: time(4320h) //6meseci
        Number(intValue >= 2) from accumulate(
            $d : NeizlecenaBolestVoca(this != $neizlecen_bolest,
                                          biljka.id == $biljka.id,
                                          this meets[4320h] $neizlecen_bolest //6 month
                                         ), 
                                          count($d)
        ) 
         not (UgrozenaBiljka(biljka == $biljka, $faza: fazaBiljke))
    then
        System.out.println("UgrozenaBiljkAlarma " + $biljka.getId());
        insert(new UgrozenaBiljka($biljka, $fazaBiljke));
       
end;


rule "UgrozenaBiljka u fazi cvetanja -preporuka za dodatne proizvode"
    no-loop 
    when    
        $alarm: UgrozenaBiljka($biljka: biljka,
                                    $fazaBiljke: fazaBiljke,
                                    fazaBiljke == FazaBiljke.CVETANJE)
    
            $finalna_dijagnoza: FinalnaDijagnoza(
                                          biljka.id == $biljka.id,
                                          fazaBiljke == $fazaBiljke,
                                          $preporuka: preporuka,
                                          this meets[5m] $alarm //sada
                                         )
    then
        $preporuka.modifyMessage("Vaša biljka je ugrožena, preporučuje se upotreba pomoćnih preparata FOLIGAL BOR, FOLIGAL MANGAN I FOLIGAL CINK");
        System.out.println("UgrozenaBiljkAlarma cvetanje" + $biljka.getId());
        modify($finalna_dijagnoza){
            setPreporuka($preporuka)
        };

end;


rule "UgrozenaBiljka u fazi listanja  -preporuka za dodatne proizvode"
    no-loop
    when    
        $alarm: UgrozenaBiljka($biljka: biljka,
                                    $fazaBiljke: fazaBiljke,
                                    fazaBiljke == FazaBiljke.LISTANJE)
    
        $finalna_dijagnoza: FinalnaDijagnoza( biljka.id == $biljka.id,
                                    fazaBiljke == $fazaBiljke,
                                    $preporuka: preporuka,
                                    this meets[5m] $alarm //sada
                                         ) //dodati neki alarm ili stanje ovde
    then
        $preporuka.modifyMessage("Vaša biljka je ugrožena, preporučuje se upotreba pomoćnih preparata FOLIGAL BOR i FOLIGAL CINK");
        System.out.println("UgrozenaBiljkAlarma listanje" + $finalna_dijagnoza.getPreporuka().getPoruka());
        modify($finalna_dijagnoza){
            setPreporuka($preporuka)
        };
end;