import com.ftn.sbnz.model.Bolest;
import com.ftn.sbnz.model.Simptom;
import com.ftn.sbnz.model.TipBiljke;
import com.ftn.sbnz.model.UnosSimptoma;
import com.ftn.sbnz.model.enums.FazaBiljke;
import com.ftn.sbnz.model.enums.Lokacija;

query poklapanjeSimptomaBolesti(Bolest $bolest, FazaBiljke $trenutnaFazaBiljke,  List<Simptom> $simptomiBiljke)
    $bolest: Bolest(naziv == $bolest.naziv,
                    $trenutnaFazaBiljke contains fazaJavljanja,
                    $simptomiBolesti: simptomi),
    Number($brojSimptoma: intValue >= 0.5 * $simptomiBolesti.size()) from accumulate (
        Simptom($s: this, this memberOf $simptomiBolesti) from $simptomiBiljke,
        count($s)
    )
end

rule "Dijagnoza bolesti na osnovu simptoma, kategorije i trenutne faze biljke"
    when 
        $unos: UnosSimptoma($simptomi: simptomi, $trenutnaFazaBiljke: trenutnaFaza, $idBiljke: idBiljke, $tip: tip),
        poklapanjeSimptomaBolesti(
            Bolest($b: this) from $tip.moguceBolesti, $trenutnaFazaBiljke, $simptomi 
        )
    then
        System.out.println($b.naziv)
end